<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<%@ page import="com.cs336.pkg.ApplicationDB" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Airport Flight Listing</title>
</head>
<body>
<% 
try {
	
	//Get the database connection
	ApplicationDB db = new ApplicationDB();	
	Connection con = db.getConnection();
	

	//Create a SQL statement
	Statement departureStmt = con.createStatement();

	String flightNumber = request.getParameter("FlightNumber");
	String airlineId = request.getParameter("Airline");
	String customerName = request.getParameter("CustomerName");
	String query;
	if(customerName == null) {
		query = "SELECT Ticket.ticket_number, Ticket.total_fare " +
					"FROM Ticket NATURAL JOIN Subticket " +
					"WHERE Subticket.airline_id = '" + airlineId + "'";
		if(flightNumber == null || flightNumber.length() == 0) {
			out.print("<h1> Revenue generated by airline " + airlineId + "</h1>");		
		} else {
			query += " AND Subticket.flight_number = " + flightNumber;
			out.print("<h1> Revenue generated by " + flightNumber + " on airline " + airlineId + "</h1>");
		}
	} else {
		query = "SELECT Ticket.ticket_number, Ticket.total_fare " +
				"FROM Person NATURAL JOIN Customer NATURAL JOIN makes NATURAL JOIN Reservation NATURAL JOIN reserves NATURAL JOIN Ticket " +
				"WHERE Person.person_name = '" + customerName + "'";
		out.print("<h1> Revenue Generated by " + customerName + "</h1>");
	}
	
	ResultSet result = departureStmt.executeQuery(query);

	out.print("<table><tr><th> Ticket Number </th> <th>Revenue Generated</th></tr>");
	while (result.next()) {
		out.print("<tr><td>");
		out.print(result.getInt(1));
		out.print("</td><td>");
		out.print(result.getInt(2));
		out.print("</td></tr>");
	}
	out.print("</table>");
} catch (Exception e) {
	out.print("Log in Failed<br>");

	out.print("Error message" + e);
	out.print(Arrays.asList(e.getStackTrace()));
}
%>
</body>
